### ISSUE TITLE
info_extractor function problem

### ISSUE THREAD

**Issue by C1ark** [yasoob/watchcartoononline-dl#3]
> kix@KiXBoX:~/watchcartoononline-dl$ python watch-dl.py 
url ?  http://www.watchcartoononline.com/pokemon-season-1-episode-2
Traceback (most recent call last):
  File "watch-dl.py", line 84, in <module>
    final_url = info_extractor(url)
  File "watch-dl.py", line 24, in info_extractor
    return urllib.unquote(final_url[-1]).replace(' ','%20')
IndexError: list index out of range
kix@KiXBoX:~/watchcartoononline-dl$ python watch-dl.py 
url ?  http://www.watchcartoononline.com/pokemon-season-1-episode-1
Traceback (most recent call last):
  File "watch-dl.py", line 84, in <module>
    final_url = info_extractor(url)
  File "watch-dl.py", line 24, in info_extractor
    return urllib.unquote(final_url[-1]).replace(' ','%20')
IndexError: list index out of range
kix@KiXBoX:~/watchcartoononline-dl$ 

Just cloned this repo and just, couldn't get it to work. Not sure If this project is abandoned but, thought I would give writing a issue a shot.

**Comment by RavetcoFX** [comment]
My pull req fixes this issue, in the meantime, remove the extra comma on line 22: 
final_url =  re.findall(r'file: "(.+?)",',    
with
final_url =  re.findall(r'file: "(.+?)"',

**Comment by C1ark** [comment]
That appears to of have fixed my issue. Thanks for the help.
